[build]
  command = "npm run build && npm run export"
  publish = "out"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
