import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BackgroundAnimation from "@/components/BackgroundAnimation";
import AIBotBox from "@/components/AIBotBox";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gradient-to-b from-slate-900 to-gray-900`}
      >
        <BackgroundAnimation>{children}</BackgroundAnimation>
        <AIBotBox />
      </body>
    </html>
  );
}
