import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import BackgroundAnimation from "@/components/BackgroundAnimation";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gradient-to-b from-slate-900 to-gray-900`}
      >
        <BackgroundAnimation>{children}</BackgroundAnimation>
      </body>
    </html>
  );
}
